apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: ticketing
build:
  googleCloudBuild:
    projectId: ticketing-dev-407610
  artifacts:
    - image: us.gcr.io/ticketing-dev-407610/auth
    # - image: quado2/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/***/*.ts"
            dest: .
    # - image: quado2/client
    - image: us.gcr.io/ticketing-dev-407610/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "***/*.js"
            dest: .
manifests:
  rawYaml:
    - infra/k8s/auth-depl.yaml
    - infra/k8s/ingress-srv.yaml
    - infra/k8s/auth-mongo-depl.yaml
    - infra/k8s/client-depl.yaml
